<?php
/**
 * @file
 * Provide an accordion display style for Views.
 *
 * This is a placeholder file so backdrop will enable the module. All logic is
 * contained in other files located with the module.
 */

/**
 * Implements hook_views_api().
 */
function views_accordion_views_api() {
  return array(
    'api' => 3,
    'path' => backdrop_get_path('module', 'views_accordion') . '/templates',
    'template path' => backdrop_get_path('module', 'views_accordion') . '/templates',
  );
}

/**
 * Template function for views_accordion style plugin.
 *
 * @param array $vars
 *   Array of template variables.
 *
 * The JS file is loaded within render() in views_accordion_style_plugin.inc
 */
function template_preprocess_views_view_accordion(&$vars) {
  // Inherit the normal unformatted classes.
  template_preprocess_views_view_unformatted($vars);

  $vars['use_group_header'] = $vars['options']['use-grouping-header'];

  // The template variable 'view_accordion_id' MUST be the same as $accordion_id
  // in the render() function inside the style plugin.
  // Don't touch it or it will stop working.
  $vars['view_accordion_id'] = 'views-accordion-' . $vars['view']->name . '-' . $vars['view']->current_display . '-header';

  // Add the css for fixing/preventing accordion issues.
  backdrop_add_css(backdrop_get_path('module', 'views_accordion') . '/css/views-accordion.css');
}

/**
 * Only returns true the first time it's called for an id.
 *
 * @param string $id
 *   A unique view id.
 *
 * @return bool
 *   TRUE for the first time called for a given $id
 *   FALSE for each time after that
 */
function theme_views_accordion_display_item($id) {
  // TODO: Should this theme views_accordion_display_item be declared in hook_theme()?
  static $display = array();

  if (!isset($display[$id])) {
    $display[$id] = FALSE;
  }

  $output = $display[$id];

  if ($display[$id] == FALSE) {
    $display[$id] = TRUE;
  }

  return $output;
}

/**
 * Implements hook_autoload_info().
 */
function views_accordion_autoload_info() {
  return array(
    'views_accordion_style_plugin' => 'views_accordion_style_plugin.inc',
  );
}
